function generateAuditReport({ orgName = 'Organization', scanResults = [], gapAnalysis = null, breachNotifications = [], classificationResults = [] }) {
  const now = new Date().toISOString();
  const reportId = `RPT-${now.slice(0, 10).replace(/-/g, '')}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`;

  const avgRisk = scanResults.length
    ? Math.round(scanResults.reduce((sum, s) => sum + (s.riskScore || 0), 0) / scanResults.length)
    : 0;

  const isoPercent  = gapAnalysis?.iso27001?.compliancePercent ?? null;
  const dpdpPercent = gapAnalysis?.dpdp?.compliancePercent ?? null;
  const overallPct  = gapAnalysis?.overallCompliancePercent ?? null;
  const criticalPiiDocs = classificationResults.filter(c => c.classificationLabel === 'RESTRICTED').length;

  return {
    reportId,
    generatedAt: now,
    organization: orgName,
    reportPeriod: {
      from: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
      to: now.slice(0, 10),
    },
    executiveSummary: {
      overallComplianceScore: overallPct,
      averageRiskScore: avgRisk,
      riskLevel: avgRisk >= 70 ? 'High' : avgRisk >= 40 ? 'Medium' : 'Low',
      totalScansRun: scanResults.length,
      restrictedDocumentsFound: criticalPiiDocs,
      classificationJobsRun: classificationResults.length,
      breachNotificationsFiled: breachNotifications.length,
      isoCompliancePercent: isoPercent,
      dpdpCompliancePercent: dpdpPercent,
      criticalGapsCount: gapAnalysis?.criticalGaps?.length ?? 0,
    },
    isoCompliance: gapAnalysis?.iso27001 ?? null,
    dpdpCompliance: gapAnalysis?.dpdp ?? null,
    dataClassification: {
      totalScanned: classificationResults.length,
      byLabel: groupBy(classificationResults, 'classificationLabel'),
      piiTypesFound: [...new Set(classificationResults.flatMap(c => c.piiFindings?.map(f => f.label) ?? []))],
    },
    recentScans: scanResults.slice(0, 10),
    breachNotifications: breachNotifications.slice(0, 10),
    topRecommendations: buildRecommendations(gapAnalysis, avgRisk, criticalPiiDocs),
    disclaimer: 'This report is generated by CompliYUG and is advisory in nature. It does not constitute legal advice. Engage qualified legal and compliance counsel for formal assessments.',
  };
}

function buildRecommendations(gapAnalysis, avgRisk, criticalDocs) {
  const recs = [];
  if (avgRisk >= 70) {
    recs.push({ priority: 'Critical', action: 'Immediately review high-risk items flagged by the compliance scanner and initiate incident response procedures', framework: 'ISO A.5.24, DPDP Section 40' });
  }
  if (criticalDocs > 0) {
    recs.push({ priority: 'Critical', action: `Apply field-level encryption and restrict access to ${criticalDocs} RESTRICTED document(s) containing PII`, framework: 'DPDP Rule 6(1)(a), ISO A.8.24' });
  }
  if (gapAnalysis?.criticalGaps?.length > 0) {
    for (const gap of gapAnalysis.criticalGaps.slice(0, 3)) {
      recs.push({ priority: 'High', action: gap.remediation, framework: gap.id ?? gap.section });
    }
  }
  if (recs.length < 3) {
    recs.push({ priority: 'Medium', action: 'Schedule annual ISO 27001 internal audit and gap assessment', framework: 'ISO A.5.35' });
    recs.push({ priority: 'Medium', action: 'Deploy mandatory security awareness training via Microsoft Viva Learning', framework: 'ISO A.6.3' });
    recs.push({ priority: 'Medium', action: 'Configure Microsoft Purview DLP to prevent data leakage via Teams, email, and SharePoint', framework: 'ISO A.8.12, DPDP Rule 6(1)(a)' });
  }
  return recs;
}

function groupBy(arr, key) {
  return arr.reduce((acc, item) => {
    const k = item[key] ?? 'Unknown';
    acc[k] = (acc[k] || 0) + 1;
    return acc;
  }, {});
}

function reportToCsv(report) {
  const rows = [
    ['CompliYUG DPDP & ISO Compliance Audit Report'],
    ['Report ID', report.reportId],
    ['Generated At', report.generatedAt],
    ['Organization', report.organization],
    ['Period From', report.reportPeriod?.from ?? ''],
    ['Period To', report.reportPeriod?.to ?? ''],
    [],
    ['EXECUTIVE SUMMARY'],
    ['Overall Compliance Score', `${report.executiveSummary.overallComplianceScore ?? 'N/A'}%`],
    ['ISO 27001 Compliance', `${report.executiveSummary.isoCompliancePercent ?? 'N/A'}%`],
    ['DPDP Act Compliance', `${report.executiveSummary.dpdpCompliancePercent ?? 'N/A'}%`],
    ['Average Risk Score', report.executiveSummary.averageRiskScore],
    ['Risk Level', report.executiveSummary.riskLevel],
    ['Critical Gaps', report.executiveSummary.criticalGapsCount],
    ['Restricted Documents Found', report.executiveSummary.restrictedDocumentsFound],
    ['Total Scans Run', report.executiveSummary.totalScansRun],
    ['Breach Notifications Filed', report.executiveSummary.breachNotificationsFiled],
    [],
    ['ISO 27001:2022 CONTROL GAP ANALYSIS'],
    ['Control ID', 'Control Name', 'Domain', 'Status', 'Remediation Action'],
  ];

  for (const c of (report.isoCompliance?.controls ?? [])) {
    rows.push([c.id, c.name, c.domain, c.status.toUpperCase(), c.remediation ?? 'No action required']);
  }

  rows.push([]);
  rows.push(['DPDP ACT & RULES 2025 REQUIREMENTS']);
  rows.push(['Section / Rule', 'Requirement', 'Status', 'Remediation Action']);

  for (const r of (report.dpdpCompliance?.requirements ?? [])) {
    rows.push([r.section, r.name, r.status.toUpperCase(), r.remediation ?? 'No action required']);
  }

  rows.push([]);
  rows.push(['TOP RECOMMENDATIONS']);
  rows.push(['Priority', 'Action', 'Framework Reference']);
  for (const rec of (report.topRecommendations ?? [])) {
    rows.push([rec.priority, rec.action, rec.framework]);
  }

  rows.push([]);
  rows.push(['DISCLAIMER', report.disclaimer]);

  return rows
    .map(row => row.map(cell => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(','))
    .join('\r\n');
}

module.exports = { generateAuditReport, reportToCsv };
